include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    use_build_context_synchronously: false
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    use_super_parameters: true
    depend_on_referenced_packages: false
    avoid_function_literals_in_foreach_calls: false
