name: homie_studio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # state
  provider: ^6.0.3
  # navigation
  go_router: ^14.2.7
  # style & assets
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  responsive_sizer: ^3.1.1
  reorderables: ^0.6.0
  styled_text: ^8.1.0
  just_the_tooltip: ^0.0.12
  scrollable_positioned_list: ^0.3.8
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  # notifications
  awesome_notifications: ^0.9.3+1
  bot_toast: ^4.0.4
  # others
  collection: ^1.17.1
  url_launcher: ^6.1.10
  intl: ^0.19.0
  flutter_cache_manager: ^3.3.1
  requests: ^4.7.0
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.2
  flutter_blue_plus: ^1.35.0

dependency_overrides:
  http: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#fafafc"
  color_dark: "#1b1d1c"
  image: "assets/images/logo.png"
  branding: "assets/images/homie.png"
  fullscreen: true
#
# dart run flutter_launcher_icons
# dart run flutter_native_splash:create
# dart run change_app_package_name:main com.homie.app

