Map<String, String> patternsMap = {
  'p1101': "Raibow Cycle",
  'p1201': "RGB Loop",
  'p1301': "Fire",
  'p1401': "Bounce 3",
  'p1402': "Bounce 6",
  'p1501': "Colored Bounce 3",
  'p1502': "Colored Bounce 6",
  'p1601': "Running Lights",
  'p1701': "Cyclon Bounce",
  'p1801': "New KITT",
  'p1901': "Strobe",
  'p2001': "Sparkle",
  'p2002': "Sparkle Random",
  'p2003': "Pine Sparkle",
  'p2101': "Snow Sparkle",
  'p2102': "Snow Sparkle Random",
  'p2201': "Twinkle",
  'p2301': "Twinkle Random",
  'p2401': "Theater Chase",
  'p2501': "Theater Rainbow",
  'p2601': "Color Wipe",
  'p2602': "Color Wipe Main",
  'p2603': "Color Wipe Random",
  'p2701': "Halloween Eyes",
  'p2702': "Halloween Eyes Main",
  'p2801': "Meteor Rain",
  'p2901': "Meteor Shower",
  'p3001': "Party Of Colors",
  'p3101': "Mini Lamp",
};

List<String> buttonPatterns = ["p1101", "p1201", "p1301", "p1401", "p1501", "p1601", "p1801", "p2301", "p2602"];

class PatternObject {
  const PatternObject({required this.code, required this.title});
  final String code;
  final String title;
}

const List<PatternObject> patternList = <PatternObject>[
  PatternObject(title: "Rainbow Cycle", code: 'p1101'),
  PatternObject(title: "RGB Loop", code: 'p1201'),
  PatternObject(title: "Fire", code: 'p1301'),
  PatternObject(title: "Bounce 3", code: 'p1401'),
  PatternObject(title: "Bounce 6", code: 'p1402'),
  PatternObject(title: "Colored Bounce 3", code: 'p1501'),
  PatternObject(title: "Colored Bounce 6", code: 'p1502'),
  PatternObject(title: "Running Lights", code: 'p1601'),
  PatternObject(title: "Cylon Bounce", code: 'p1701'),
  PatternObject(title: "New KITT", code: 'p1801'),
  PatternObject(title: "Strobe", code: 'p1901'),
  PatternObject(title: "Sparkle", code: 'p2001'),
  PatternObject(title: "Sparkle Random", code: 'p2002'),
  PatternObject(title: "Pine Sparkle", code: 'p2003'),
  PatternObject(title: "Snow Sparkle", code: 'p2101'),
  PatternObject(title: "Snow Sparkle Random", code: 'p2102'),
  PatternObject(title: "Twinkle", code: 'p2201'),
  PatternObject(title: "Twinkle Random", code: 'p2301'),
  PatternObject(title: "Theater Chase", code: 'p2401'),
  PatternObject(title: "Theater Rainbow", code: 'p2501'),
  PatternObject(title: "Color Wipe", code: 'p2601'),
  PatternObject(title: "Color Wipe Main", code: 'p2602'),
  PatternObject(title: "Color Wipe Random", code: 'p2603'),
  PatternObject(title: "Halloween Eyes", code: 'p2701'),
  PatternObject(title: "Halloween Eyes Main", code: 'p2702'),
  PatternObject(title: "Meteor Rain", code: 'p2801'),
  PatternObject(title: "Meteor Shower", code: 'p2901'),
  PatternObject(title: "Party Of Colors", code: 'p3001'),
  PatternObject(title: "Mini Lamp", code: 'p3101'),
];
