import '../../../_models/effect.dart';

const List<Effect> hubPatterns = <Effect>[
  Effect(title: 'Bit', code: 'pbit0'),
  Effect(title: 'Bit Color', code: 'pbit1'),
  Effect(title: 'Bounce 3', code: 'pbob3'),
  Effect(title: 'Bounce 6', code: 'pbob6'),
  Effect(title: 'Bounce Color 3', code: 'pbcb3'),
  Effect(title: 'Bounce Color 6', code: 'pbcb6'),
  Effect(title: 'BPM', code: 'pbpms'),
  Effect(title: 'Colorwipe RGB', code: 'pcow0'),
  Effect(title: 'Colorwipe Main', code: 'pcow1'),
  Effect(title: 'Colorwipe Random', code: 'pcow2'),
  // Effect(title: 'Color Jar', code: 'pp29'),
  // Effect(title: 'Color Fly', code: 'pp30'),
  Effect(title: 'Confetti', code: 'pconf'),
  Effect(title: 'Cylon Bounce', code: 'pcycb'),
  Effect(title: 'Fire', code: 'pfire'),
  // Effect(title: 'Fill', code: 'pp36'),
  Effect(title: 'Halloween Eyes', code: 'phal0'),
  Effect(title: 'Halloween Eyes Main', code: 'phal1'),
  Effect(title: 'Juggle', code: 'pjug0'),
  Effect(title: 'Juggle Mini', code: 'pjug2'),
  // Effect(title: 'Matrix 1', code: 'pp46'),
  Effect(title: 'Meteor Rain', code: 'pmetr'),
  Effect(title: 'Meteor Shower', code: 'pmets'),
  Effect(title: 'Mini Boss', code: 'pminb'),
  Effect(title: 'New KITT', code: 'pnewk'),
  Effect(title: 'Pacifica', code: 'ppacf'),
  Effect(title: 'Party Of Colors', code: 'ppaco'),
  Effect(title: 'Palette', code: 'ppalt'),
  // Effect(title: "---", code: 'pp23'),
  Effect(title: 'Pride', code: 'pprid'),
  Effect(title: 'Rainbow Cycle', code: 'pracy'),
  Effect(title: 'Rainbow Run', code: 'praru'),
  Effect(title: 'RGB Loop', code: 'prgbl'),
  Effect(title: 'Ripple', code: 'prip0'),
  Effect(title: 'Ripple 1', code: 'prip1'),
  Effect(title: 'Running Lights', code: 'prunl'),
  Effect(title: 'Sinelon', code: 'psinl'),
  Effect(title: 'Sinelon Random', code: 'psinr'),
  Effect(title: 'Sinelon 2', code: 'psin2'),
  Effect(title: 'Snow Sparkle', code: 'psnsp'),
  Effect(title: 'Sparkle', code: 'pspk0'),
  Effect(title: 'Sparkle Main', code: 'pspk1'),
  Effect(title: 'Sparkle Random', code: 'pspk2'),
  Effect(title: 'Strobe', code: 'pstrb'),
  Effect(title: 'Theater Chase', code: 'pthch'),
  Effect(title: 'Theater Chase Rainbow', code: 'pthcr'),
  Effect(title: 'Twinkle', code: 'ptwn0'),
  Effect(title: 'Twinkle Random', code: 'ptwn1'),
  Effect(title: 'Twinkle 2', code: 'ptwn2'),
  Effect(title: 'Zoom', code: 'pzoom'),
];
