import '../../../_models/effect.dart';

const List<Effect> hubPatterns = <Effect>[
  Effect(title: 'Bit', code: 'p0'),
  Effect(title: 'Bit Color', code: 'p1'),
  Effect(title: 'Bounce 3', code: 'p2'),
  Effect(title: 'Bounce 6', code: 'p3'),
  // Effect(title: "Bounce Color 3", code: 'p4'),
  // Effect(title: "Bounce Color 6", code: 'p5'),
  Effect(title: 'BPM', code: 'p6'),
  Effect(title: 'Colorwipe RGB', code: 'p8'),
  Effect(title: 'Colorwipe Main', code: 'p9'),
  Effect(title: 'Colorwipe Random', code: 'p10'),
  Effect(title: 'Color Jar', code: 'p29'),
  Effect(title: 'Color Fly', code: 'p30'),
  Effect(title: 'Confetti', code: 'p7'),
  Effect(title: 'Cylon Bounce', code: 'p11'),
  Effect(title: 'Fire', code: 'p12'),
  Effect(title: 'Fill', code: 'p36'),
  Effect(title: 'Halloween Eyes', code: 'p13'),
  Effect(title: 'Halloween Eyes Main', code: 'p14'),
  Effect(title: 'Juggle', code: 'p15'),
  Effect(title: 'Juggle Mini', code: 'p16'),
  Effect(title: 'Matrix 1', code: 'p46'),
  Effect(title: 'Matrix 2', code: 'p47'),
  Effect(title: 'Matrix 3', code: 'p48'),
  Effect(title: 'Matrix 4', code: 'p49'),
  Effect(title: 'Matrix 5', code: 'p50'),
  Effect(title: 'Meteor Rain', code: 'p17'),
  Effect(title: 'Meteor Shower', code: 'p18'),
  Effect(title: 'Mini Boss', code: 'p19'),
  Effect(title: 'New KITT', code: 'p20'),
  Effect(title: 'Pacifica', code: 'p24'),
  Effect(title: 'Palette', code: 'p21'),
  Effect(title: 'Party Of Colors', code: 'p22'),
  // Effect(title: "---", code: 'p23'),
  Effect(title: 'Pride', code: 'p25'),
  Effect(title: 'Rainbow Cycle', code: 'p26'),
  Effect(title: 'Rainbow Run', code: 'p27'),
  Effect(title: 'RGB Loop', code: 'p28'),
  Effect(title: 'Running Lights', code: 'p31'),
  Effect(title: 'Sinelon', code: 'p32'),
  Effect(title: 'Sinelon Random', code: 'p33'),
  // Effect(title: "Sinelon 2", code: 'p34'),
  Effect(title: 'Snow Sparkle', code: 'p35'),
  // Effect(title: "---", code: 'p36'),
  Effect(title: 'Sparkle', code: 'p37'),
  Effect(title: 'Sparkle Main', code: 'p38'),
  Effect(title: 'Sparkle Random', code: 'p39'),
  Effect(title: 'Strobe', code: 'p40'),
  Effect(title: 'Theater Chase', code: 'p41'),
  Effect(title: 'Theater Chase Rainbow', code: 'p42'),
  Effect(title: 'Twinkle', code: 'p43'),
  Effect(title: 'Twinkle Random', code: 'p44'),
  Effect(title: 'Twinkle 2', code: 'p45'),
];
